version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html  # Uygulaman覺z覺 konteyn覺ra kopyalay覺n
        networks:
            - laravel_network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
