version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - laravel

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_test
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
