version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8081:80"
    depends_on:
      - php
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
